// Generated by npm run diagrams:build. Do not edit by hand.
export const diagramAssets = {
  "document-overview": {
    "desktop": {
      "src": "/diagrams/document-overview-desktop.svg",
      "width": 281,
      "height": 433
    },
    "mobile": {
      "src": "/diagrams/document-overview-mobile.svg",
      "width": 281,
      "height": 433
    }
  },
  "document-pipeline": {
    "desktop": {
      "src": "/diagrams/document-pipeline-desktop.svg",
      "width": 1129,
      "height": 148
    },
    "mobile": {
      "src": "/diagrams/document-pipeline-mobile.svg",
      "width": 215,
      "height": 671
    }
  },
  "evaluation-loop": {
    "desktop": {
      "src": "/diagrams/evaluation-loop-desktop.svg",
      "width": 1091,
      "height": 274
    },
    "mobile": {
      "src": "/diagrams/evaluation-loop-mobile.svg",
      "width": 299,
      "height": 500
    }
  },
  "inventory-system": {
    "desktop": {
      "src": "/diagrams/inventory-system-desktop.svg",
      "width": 1120,
      "height": 186
    },
    "mobile": {
      "src": "/diagrams/inventory-system-mobile.svg",
      "width": 327,
      "height": 493
    }
  },
  "marketplace-matching": {
    "desktop": {
      "src": "/diagrams/marketplace-matching-desktop.svg",
      "width": 1051,
      "height": 205
    },
    "mobile": {
      "src": "/diagrams/marketplace-matching-mobile.svg",
      "width": 253,
      "height": 501
    }
  },
  "product-memory": {
    "desktop": {
      "src": "/diagrams/product-memory-desktop.svg",
      "width": 1110,
      "height": 105
    },
    "mobile": {
      "src": "/diagrams/product-memory-mobile.svg",
      "width": 216,
      "height": 493
    }
  },
  "quote-controls": {
    "desktop": {
      "src": "/diagrams/quote-controls-desktop.svg",
      "width": 1279,
      "height": 148
    },
    "mobile": {
      "src": "/diagrams/quote-controls-mobile.svg",
      "width": 220,
      "height": 754
    }
  },
  "quote-overview": {
    "desktop": {
      "src": "/diagrams/quote-overview-desktop.svg",
      "width": 276,
      "height": 358
    },
    "mobile": {
      "src": "/diagrams/quote-overview-mobile.svg",
      "width": 276,
      "height": 358
    }
  }
} as const;
