import { Figure, Arrow } from '@/components/diagrams/Figure';
import { FlowDiagram } from '@/components/diagrams/FlowDiagram';
import { BeforeAfter } from '@/components/diagrams/BeforeAfter';
import { ConceptCurve } from '@/components/diagrams/ConceptCurve';
import { TradeoffSpectrum } from '@/components/diagrams/TradeoffSpectrum';
import { Matrix2x2 } from '@/components/diagrams/Matrix2x2';

/** Case-specific compositions of the shared primitives. All labels come from the v2 brief. */
export function CaseFigure({ id, caseStudy }: { id: string; caseStudy: string }) {
  if(id==='concept-curve')return <ConceptCurve caseStudy={caseStudy}/>;
  if(id==='customization-spectrum')return <TradeoffSpectrum caseStudy={caseStudy}/>;
  if(id==='trust-matrix')return <Matrix2x2 caseStudy={caseStudy}/>;
  if(id==='failure-taxonomy')return <Figure id={id} caseStudy={caseStudy} caption="The failures weren't about format. They were about meaning."><div className="taxonomy">{['Field meaning ambiguous','Layout variant','Table structure','Scan quality'].map((label,i)=><div key={label}><svg viewBox="0 0 160 84" role="img" aria-label={`Illustrative failure category: ${label}`}><rect x="14" y="13" width="85" height="58" rx="5" className="taxonomy-sheet"/><rect x={38+i*7} y="29" width="104" height="26" rx="4" className="taxonomy-region"/></svg><strong>{label}</strong></div>)}</div></Figure>;
  if(id==='eval-stack')return <Figure id={id} caseStudy={caseStudy} caption="Evaluation made a hard trade-off discussable."><div className="eval-stack"><div className="eval-tiers">{['Online monitoring in production','Human review: 50 reviewers whose corrections flow back as structured signal','LLM-as-judge scoring','Per-tenant golden sets, seeded with production samples, gate every release'].map((tier,i)=><div key={tier}><span className="tier-index" aria-hidden="true">{4-i}</span><strong>{tier}</strong></div>)}</div><div className="eval-measurements"><svg viewBox="0 0 24 260" role="img" aria-label="The four evaluation layers share measurement criteria"><path d="M18 5H6V255H18" className="axis"/></svg><div><span className="spec-label">Measured</span><ul><li>Field-level accuracy</li><li>Hallucination rate</li><li>Confidence calibration</li></ul></div></div></div></Figure>;
  if(id==='document-pipeline')return <FlowDiagram id={id} caseStudy={caseStudy} caption="Confidence thresholds decided what passed automatically and what needed a person." nodes={[{label:'Ingest and batch split'},{label:'Native-text-first parsing'},{label:'Classify'},{label:'Hybrid retrieval',tone:'science'},{label:'Extract',badge:'p50 1.2s on the extraction step'},{label:'Confidence check',tone:'craft'}]} branches={[{label:'High: validated output',tone:'science'},{label:'Low: re-extract at 150 → 200 → 300 DPI',detail:'Still low: human review',tone:'craft'}]} tail={[{label:'Postgres'},{label:'Client systems'}]}/>;
  if(id==='table-stitch')return <Figure id={id} caseStudy={caseStudy} caption="Tables that spanned page breaks broke the assumption that a page is a unit of meaning."><div className="table-stitch"><svg viewBox="0 0 470 460" role="img" aria-label="Illustrative: a table spans two source pages and is treated as one logical table"><rect x="30" y="15" width="255" height="192" rx="7" className="document-paper"/><rect x="30" y="243" width="255" height="192" rx="7" className="document-paper"/><path d="M52 45H251M52 59H214M52 371H246M52 386H228" className="document-line"/>{[108,140,172,265,297,329].map(y=><g key={y}><rect x="51" y={y} width="214" height="25" className="table-row"/><path d={`M121 ${y}v25M193 ${y}v25`} className="document-line"/></g>)}<path d="M310 108h25v246h-25M337 226h81m-8-8 8 8-8 8" className="curve science"/><path d="M17 225H285" className="page-break"/></svg><div><span className="reason-chip science">Table structure</span><strong>A single logical table</strong><span>Across the page break</span></div></div></Figure>;
  if(id==='inventory-hub')return <Figure id={id} caseStudy={caseStudy} caption="Build the model first. Make every connector configuration."><div className="inventory-hub"><div className="hub-sources">{['Tally','Zoho','Vyapar','Custom systems'].map(source=><span key={source}>{source}</span>)}</div><Arrow label="Existing systems share a canonical model"/><div className="hub-model"><strong>Canonical model</strong><ul>{['Item master','UoM','Multi-location','Batch/lot','Transaction types'].map(x=><li key={x}>{x}</li>)}</ul></div><Arrow label="Configure mappings for dashboards and alerts"/><div className="hub-destination"><strong>Config-driven mappings</strong><span>Dashboards and alerts</span></div></div></Figure>;
  if(id==='sync-trust')return <FlowDiagram id={id} caseStudy={caseStudy} caption="A silent failure is worse than a loud one." nodes={[{label:'Local sync agent'},{label:'Cloud aggregation'},{label:'Continuous reconciliation vs source ERP',tone:'science'},{label:'Silent-sync-failure detection',tone:'risk'},{label:'Alert',tone:'craft'}]}/>;
  if(id==='quote-pipeline')return <FlowDiagram id={id} caseStudy={caseStudy} caption="Automate the loop. Keep humans on the edges." nodes={[{label:'RFQ intake'},{label:'Intent classification'},{label:'Part number extraction'},{label:'Inventory matching'},{label:'Pricing',badge:'Price-floor guardrail',tone:'craft'},{label:'Confidence tier',tone:'science'}]} branches={[{label:'Auto-quote',tone:'science'},{label:'Human review',tone:'craft'},{label:'Escalate',tone:'risk'}]} tail={[{label:'Quote-to-order'}]} rail="Human override"/>;
  if(id==='account-context')return <Figure id={id} caseStudy={caseStudy} caption="The fix wasn't a better prompt. It was modeling the account."><div className="account-model"><div className="isolated-rfq"><span className="spec-label risk">RFQ as a standalone request</span><svg viewBox="0 0 240 200" role="img" aria-label="A standalone RFQ is isolated from the account"><circle cx="120" cy="100" r="54" className="isolated-node"/><text x="120" y="106" textAnchor="middle">RFQ</text></svg></div><div className="connected-rfq"><span className="spec-label science">RFQ as account context</span><div className="account-center">RFQ</div><svg viewBox="0 0 360 35" role="img" aria-label="The RFQ connects to eight dimensions of account context"><path d="M180 1v16M24 34V17H336V34M120 17v17M240 17v17" className="axis"/></svg><ul>{['Prior quotes','Sister entities','Pricing tier','Relationship history','Revenue risk','Lead time','Alternates','NPI vs repeat'].map(item=><li key={item}>{item}</li>)}</ul></div></div></Figure>;
  if(id==='quote-before-after')return <div className="comparison-pair"><BeforeAfter id="in-stock-before-after" caseStudy={caseStudy} before="18h" after="<1h" label="In-stock time to quote" caption="In-stock time to quote went from 18 hours to under 1 hour."/><BeforeAfter id="out-of-stock-before-after" caseStudy={caseStudy} before="15d" after="<3d" label="Out-of-stock turnaround" caption="Out-of-stock turnaround went from 15 days to under 3."/></div>;
  if(id==='launch-fork')return <Figure id={id} caseStudy={caseStudy} caption="Fight for the harder path, and prove it fast."><div className="launch-fork"><div className="risk"><s>Lift-and-shift the India matching model</s></div><Arrow label="Choose US-specific matching"/><div className="science"><strong>US-specific matching for collaborative learning</strong></div></div><div className="proof-window"><span className="spec-label">Three-week proof window</span><ol>{['Hypothesis','Evidence','Decision','Launch'].map((item,i)=><li key={item}><strong>{item}</strong>{i<3&&<Arrow label={`Continue after ${item.toLowerCase()}`}/>}</li>)}</ol></div></Figure>;
  if(id==='matching-flow')return <FlowDiagram id={id} caseStudy={caseStudy} caption="A 60-second promise, kept in 45." nodes={[{label:'Student request'},{label:'OCR intake'},{label:'US-specific matching',tone:'science'},{label:'Tutor accepts'},{label:'Live session',badge:'Session continuity',detail:'Low-bandwidth audio/video'}]}><div className="latency-budget"><div><strong>98% of US requests</strong><span>Matched in under 45 seconds</span></div><svg viewBox="0 0 900 65" role="img" aria-label="A marker at 45 seconds against the 60-second matching target"><path d="M12 28H888" className="spectrum-track"/><path pathLength="1" d="M12 28H669" className="curve science draw-path"/><path d="M669 12v32M888 12v32" className="axis"/></svg><div className="latency-labels"><span>45s</span><span>60s target</span></div></div></FlowDiagram>;
  if(id==='marketplace-trust')return <Figure id={id} caseStudy={caseStudy} caption="Matching had a 60-second target. We designed the whole request path around it."><div className="marketplace-trust"><strong>Students</strong><Arrow label="Students enter the marketplace trust layer"/><div>{['Onboarding','Quality thresholds','Fraud detection'].map(item=><span key={item}>{item}</span>)}</div><Arrow label="The trust layer also applies to tutors"/><strong>Tutors</strong></div></Figure>;
  throw new Error(`Unknown case figure: ${id}`);
}
