import type { CaseStudy } from '@/content/case-studies';
import { Figure, Arrow } from '@/components/diagrams/Figure';

function DocumentPreview() {
  return <svg className="document-preview" viewBox="0 0 420 490" role="img" aria-label="Illustrative document with five highlighted source regions for the extracted fields"><rect x="24" y="10" width="372" height="466" rx="4" className="document-paper"/><text x="51" y="49">Sample document</text><path d="M51 72H281M51 82H326" className="document-line"/>{['Product name', 'Batch / lot', 'Quantity', 'Required date', 'Source'].map((label, i) => <g key={label}><rect x="43" y={111+i*62} width={i===2?259:316} height="43" rx="3" className={i===2?'highlight-amber':'highlight-blue'}/><text x="55" y={136+i*62}>{label}</text></g>)}</svg>;
}
function ReviewArtifact() {
  const fields=[['Product name','Sample Compound A','High'],['Batch / lot','Sample lot A','High'],['Quantity','Sample quantity','Low'],['Required date','Sample date','High'],['Source','Sample document','High']];
  return <div className="review-artifact"><div className="source-pane"><span className="artifact-label">Source document</span><DocumentPreview/></div><div className="field-pane"><div className="artifact-toolbar"><strong>Extracted fields</strong><span>Human review</span></div><div className="field-list">{fields.map(([field,value,confidence])=><div key={field} className={confidence==='Low'?'field-needs-review':''}><div><span>{field}</span><strong>{value}</strong>{confidence==='Low'&&<small>re-extracted at 300 DPI</small>}</div><span className={`confidence ${confidence.toLowerCase()}`}>{confidence}</span></div>)}</div><div className="artifact-note">Every extracted value traces back to its source.</div></div></div>;
}
function StateIcon({ state }: { state: string }) {
  return <svg viewBox="0 0 24 24" role="img" aria-label={state} className={`state-icon ${state==='Matched'?'matched':state==='Mismatch'?'mismatch':'silent'}`}><circle cx="12" cy="12" r="10" fill="none" stroke="currentColor" strokeWidth="1.5"/>{state==='Matched'?<path d="m6 12 4 4 8-9" fill="none" stroke="currentColor" strokeWidth="1.5"/>:<path d="M12 6v8m0 3v1" stroke="currentColor" strokeWidth="2"/>}</svg>;
}
function ReconciliationArtifact() {
  const rows=[['Sample SKU A','Sample balance A','Sample balance A','Matched'],['Sample SKU B','Sample balance B','Sample balance C','Mismatch'],['Sample SKU C','Source ERP balance','Closphere balance','sync silent for 6h']];
  return <div className="reconciliation-artifact"><div className="artifact-toolbar"><strong>Inventory reconciliation</strong><span>Source ERP · Closphere</span></div><div className="reconciliation-head"><span>SKU</span><span>Source ERP balance</span><span>Closphere balance</span><span>Status</span></div>{rows.map(([sku,source,balance,status])=><div className="reconciliation-row" key={sku}><strong>{sku}</strong><span data-label="Source ERP balance">{source}</span><span data-label="Closphere balance">{balance}</span><span className={`reconcile-state ${status==='Matched'?'matched':status==='Mismatch'?'mismatch':'silent'}`}><StateIcon state={status}/>{status}</span></div>)}<div className="artifact-note">Continuous reconciliation against source ERP balances, silent-failure detection.</div></div>;
}
function RfqArtifact() {
  return <div className="rfq-artifact"><div className="rfq-email"><span className="artifact-label">RFQ intake</span><h3>Sample RFQ</h3><div className="email-line"><span>Intent</span><strong>New quote</strong></div><p><mark>SAMPLE-MPN-A</mark><span className="callout-label">MPN extracted</span></p><p><mark>Sample quantity</mark><span className="callout-label">Quantity</span></p><p><mark>Sample required date</mark><span className="callout-label">Required date</span></p></div><div className="routing-panel"><span className="artifact-label">Routing decision</span><dl><div><dt>Confidence</dt><dd><span className="confidence low">Medium</span></dd></div><div><dt>Account</dt><dd>Tiered pricing</dd></div></dl><Arrow label="Medium confidence with tiered pricing routes to human review"/><strong className="review-route">Human review</strong></div></div>;
}
function MatchingArtifact() {
  return <div className="matching-artifact"><div className="phone"><span className="phone-speaker"/><span className="artifact-label">Student request</span><h3>Upload a problem</h3><svg viewBox="0 0 210 205" role="img" aria-label="Illustrative photograph of a sample problem"><rect x="12" y="15" width="186" height="173" rx="6" className="document-paper"/><path d="M30 48H176M30 64H155M30 81H168M30 160H164" className="document-line"/><path d="m58 137 40-40 51 40Z" className="axis"/></svg><span className="phone-button">OCR intake</span></div><Arrow label="Finding your tutor"/><div className="phone"><span className="phone-speaker"/><span className="artifact-label">US-specific matching</span><h3>Finding your tutor</h3><div className="countdown"><svg viewBox="0 0 180 180" role="img" aria-label="A 60-second matching target"><circle cx="90" cy="90" r="72" className="ring-track"/><circle cx="90" cy="90" r="72" className="ring-progress"/></svg><div><strong>60s</strong><span>target</span></div></div><span className="phone-caption">98% of US requests<br/>matched in under 45 seconds</span></div><Arrow label="A tutor accepts the match"/><div className="phone"><span className="phone-speaker"/><span className="artifact-label">Tutor accepts</span><h3>Matched</h3><svg className="tutor-avatar" viewBox="0 0 120 120" role="img" aria-label="Illustrative avatar for a fictional tutor"><circle cx="60" cy="60" r="58" className="avatar-bg"/><circle cx="60" cy="43" r="19" className="avatar-person"/><path d="M25 102c0-41 70-41 70 0" className="avatar-person"/></svg><strong>Sample Tutor</strong><span className="phone-button">Live session</span></div></div>;
}
export function ProductArtifact({ study }: { study: CaseStudy }) {
  return <Figure id={`${study.artifact}-artifact`} caseStudy={study.slug} caption={study.artifactCaption} className={`product-artifact artifact-${study.artifact}`}>
    {study.artifact==='review'?<ReviewArtifact/>:study.artifact==='reconciliation'?<ReconciliationArtifact/>:study.artifact==='rfq'?<RfqArtifact/>:<MatchingArtifact/>}
  </Figure>;
}
